// English Translations — Japanese base text → English
// Keys are the Japanese strings displayed as the default language.
// Values are the English equivalents shown when the user selects English.
const englishTranslations = {

    // ── 1. NAV / LINKBOX / FOOTER ────────────────────────────────────────────────
    '航空機販売': 'Aircraft Sales',
    '航空機整備': 'Maintenance',
    '輸送・サルベージ': 'Transport & Salvage',
    '改造・内装': 'Remodeling',
    '塗装': 'Painting',
    'その他': 'Other Services',
    '会社概要': 'Our Company',
    '業務実績': 'Achievements',
    'IR情報': 'Investor Relations',
    '採用情報': 'Recruitment',
    '情報セキュリティ基本方針': 'Security Policy',
    'お問い合わせ': 'Contact Us',
    'エアロラボ韓国': 'Aerolab Korea',
    'パイロットショップ': 'Pilot Shop',
    '航空スペック': 'Aircraft Specs',

    // ── 2. HOME ──────────────────────────────────────────────────────────────────
    '少年の頃から憧れた空へ': 'Towards The Skies We Have Always Dreamed Of',
    'エアロラボは、大阪・八尾空港を拠点とする航空関連企業です。航空機の販売・整備・運航を通じ、日本の空の安全と発展を支えています。専門技術者の知見と経験を活かし、機体の状態に応じた最適な対応を実施。高品質なサービスにより、安全性と効率性の両立を追求しております。部品や設備の供給にも対応し、現場のニーズに即した柔軟な支援を展開。法令や基準を遵守しながら、創意工夫により新たな価値を創出いたします。信頼されるパートナーとして、これからも独自の強みを活かし続けていきます。': 'Aerolab is an aviation company based at Yao Airport in Osaka. Through aircraft sales, maintenance, and operations, we support the safety and development of Japan\'s aviation sector. Drawing on the expertise and experience of our specialist technicians, we deliver optimal solutions tailored to each aircraft\'s condition. We pursue both safety and efficiency through high-quality service. We also handle parts and equipment supply, providing flexible on-site support. While complying with all laws and standards, we continue to create new value through innovation. As a trusted partner, we will keep leveraging our unique strengths for years to come.',
    'エアロラボでは、航空機の販売や整備に加え、関係機関との各種調整や手続きにも対応しております。専門性が求められる案件にも的確に取り組み、運用全体を円滑に進めてまいります。日本最高峰の技術力と経験豊富なスタッフが、それぞれのご要望に応じた最適な解決策をご提案いたします。': 'At Aerolab, in addition to aircraft sales and maintenance, we handle various coordination and procedures with relevant authorities. We address even highly specialized matters with precision, ensuring smooth overall operations. Our world-class technical expertise and experienced staff stand ready to propose the optimal solution for each of your needs.',
    '当社では、航空機関連事業における各種実績や取り組みを適切に開示するとともに、企業としての透明性向上に努めています。また、今後の成長を見据えた採用活動にも注力し、多様な人材の参画を推進しています。会社概要、業務実績、採用に関する詳細については、各ページよりご確認ください。': 'We are committed to appropriately disclosing our achievements and initiatives in the aviation industry while enhancing transparency as a company. We also focus on recruiting diverse talent to drive future growth. For details on our company profile, track record, and recruitment, please visit each page.',
    'エアロラボグループ各社のウェブサイトは、下のカードよりご覧いただけます。': 'You can view the websites of each Aerolab Group company via the cards below.',

    // ── 3. PAGE HEADINGS ─────────────────────────────────────────────────────────
    'エアロラボでは様々な新機/中古機を取り扱っております。現在当社で販売をしているものに関わらず、お客様のオーダーにあった機体を世界より探し、仲介することも可能です。まずは、お気軽にご連絡ください。': 'Aerolab handles a wide range of new and pre-owned aircraft. Regardless of our current inventory, we can also search globally and broker aircraft tailored to your specific requirements. Please feel free to contact us at any time.',
    'エアロラボは、現地でのトラブル対応や修理、重大な損傷時の解体・輸送に加え、フェリーフライトを活用した効率的な輸入手続きまで、一貫したサービスをご提供いたします。': 'Aerolab provides end-to-end services covering on-site troubleshooting and repairs, aircraft disassembly and transport in the event of serious damage, and efficient import procedures utilizing ferry flights.',
    'アメリカのカリフォルニア州サンノゼより日本の八尾空港への フェリーフライトです。全行程約30時間 1週間の日程です。': 'A ferry flight from San Jose, California, USA to Yao Airport, Japan. The total journey takes approximately 30 hours over a 1-week schedule.',
    '改造業務としてアビオニクス(航空機電気装備品)や内装の修理改造をいくつも実施して航空局の認可を得ています。世界トップレベルの技術により顧客の要望に応える、作業を実施してきました。': 'We have carried out numerous avionics (aircraft electrical equipment) and interior modification projects, obtaining Civil Aviation Bureau approval for each. We have consistently delivered work meeting client requirements through world-class technical expertise.',
    '耐久性と耐腐食性に優れた最先端の素材を使用しています。お客様のご要望を承り、ご相談の上、補修計画が立てられます。': 'We use state-of-the-art materials with excellent durability and corrosion resistance. We listen to your requirements and develop a customized paint job through consultation.',
    'エアロラボはそのほかにもさまざまな航空機に関連する事業を行っております。': 'Aerolab also engages in a wide range of other aviation-related businesses.',
    'このページでは、当社がこれまでに達成した主な成果や実績をご紹介しています。業界での認定や受賞歴を通じて、常に優れたサービスを提供してきたことを証明しています。これらの実績は、お客様との信頼を築き、最高品質のサポートを提供し続ける当社の姿勢を反映しています。': 'This page showcases the key achievements and milestones Aerolab has accomplished to date. Our industry certifications and awards demonstrate our consistent commitment to delivering excellent service. These accomplishments reflect our dedication to building client trust and continually providing the highest standard of support.',
    '当社の求人情報をご覧いただきありがとうございます。現在募集中のポジションは下記に掲載されています。': 'Thank you for your interest in career opportunities at Aerolab. Current open positions are listed below.',
    'ページが見つかりません（404）お探しのページは存在しないか、移動または削除された可能性があります。お手数ですが、下記のリンクから目的のページをお探しください。': 'The page you are looking for may not exist, or may have been moved or deleted. Please use the links below to find the page you are looking for.',
    '超長距離ビジネスジェット「ガルフストリームG550」の機体仕様や性能、運航コストの内訳に加え、航続距離マップをご覧いただけます。': 'View the airframe specifications, performance data, operational cost breakdown, and range map for the ultra-long-range business jet Gulfstream G550.',

    // ── 4. SALES ─────────────────────────────────────────────────────────────────
    '強み': 'Our Strengths',
    '当社スタッフが海外で買い付け': 'Our Staff Sources Aircraft Overseas',
    '国内外問わずお客様のご要望に応じて様々な国から機体を買い付けることが可能です。ご予算やご希望に応じて独自のネットワークで最高の機体をお探しいたします。さらに、外国で購入した航空機を分解輸送やフェリーフライトをすることも可能です。': 'We are able to source aircraft from various countries both domestically and internationally according to our clients\' requests. Using our unique network, we will find the best aircraft to suit your budget and requirements. We can also arrange disassembly transport or ferry flights for aircraft purchased abroad.',
    '整備から運行手続きを一貫': 'End-to-End from Maintenance to Registration',
    '買い付けた機体をプロの目でチェックし安全性等を再度確認します。国内外問わず様々な場所から日本まで輸送できることも当社の強みです。尚、ご購入いただいた機体の各種手続き（耐空証明取得、RVSM航行の許可取得、RNAV航行の許可取得や、修理改造検査（内装の変更、アビオニクスの変更）なども請け負っております。': 'We professionally inspect all sourced aircraft to re-confirm safety standards. Our ability to transport aircraft from locations worldwide to Japan is one of our key strengths. We also handle all paperwork for purchased aircrafts, including airworthiness certification, RVSM authorization, RNAV authorization, and repair/modification inspections such as interior and avionics changes.',
    '販売実績': 'Sales Highlights',
    '2006年式': '2006 Model',
    '2009年式': '2009 Model',
    '2018年式': '2018 Model',
    'お客様のご要望に基づき、ガルフストリーム G550 の導入をサポートいたしました。機体選定から条件交渉まで対応し、ご要望に適合する機体を確保しております。ご購入に際しては、必要な整備・修繕および各種手続きを確実に実施し、長距離・大陸間の国際フライトに対応可能な万全の状態で機体を引き渡しました。その後は、当社パイロットによりアメリカから日本へのフェリーフライトを安全に実施。現在は整備チームが継続的な機体整備を担当し、導入から運航・整備まで一貫した体制で支援しております。': 'We supported the purchase of the Gulfstream G550 based on the client\'s requirements, handling everything from aircraft selection to contract negotiation. Prior to delivery, all necessary maintenance, repairs, and procedures were carried out, and the aircraft was handed over in full readiness for long-range and intercontinental flights. Our pilots then safely conducted the ferry flight from the United States to Japan. The maintenance team now handles ongoing airframe upkeep, providing end-to-end support from acquisition through operations and maintenance.',
    'ガルフストリーム G200 の導入において、機体選定から詳細な点検・整備に至るまで一貫して対応し、信頼性の高い機体を確保しております。整備完了後は、当社ネットワークを活用し、アメリカにてブラックとゴールドを基調とした特別塗装を実施。品質と意匠性を両立した外観に仕上げております。なお、本機は日本での登録を行わず、米国籍機として運用することで、国内外を問わず柔軟なフライトが可能な体制を確保しております。導入後も、運航および整備の両面から継続的なサポートを提供しております。': 'For the purchase of the Gulfstream G200, we handled everything from aircraft selection to detailed inspection and maintenance, securing a highly reliable aircraft. After completing maintenance, we leveraged our network to commission a special black-and-gold livery in the United States, achieving a finish that balances quality with aesthetic appeal. The aircraft operates as a US-registered aircraft rather than being registered in Japan, enabling flexible flight operations both domestically and internationally. We continue to provide ongoing support covering both operations and maintenance.',
    'エアバス H125 ヘリコプターの売買をトータルでサポートいたしました。売却案件に対し、当社ネットワークを活用し、日本国内において本機の価値をご理解いただけるお客様とのマッチングを実現しております。機体の状態および価値を的確に評価した提案によりご成約へとつなげるとともに、耐空検査をはじめとする各種手続きを当社にて一括対応し、円滑かつ信頼性の高い取引を実現いたしました。導入に至るまでの全工程を社内で完結し、迅速かつ確実な対応を実施。導入後も運用・整備を含めた継続的なサポートを提供しております。': 'We provided total support for the sale and purchase of the Airbus H125 helicopter. For the sale, we leveraged our network to match the aircraft with a suitable buyer in Japan who fully understood its value. Our accurate appraisal of the aircraft\'s condition and worth led to a successful transaction, and we handled all related procedures—including airworthiness inspection—in-house, ensuring a smooth and reliable deal. The entire process through to delivery was completed internally with speed and precision. We continue to provide ongoing support including operations and maintenance.',
    '販売履歴': 'Sales History',

    // ── 5. MAINTENANCE ───────────────────────────────────────────────────────────
    '日本最高峰の技術': "Japan's Best",
    '当社では修理、日常点検、50/100時間点検等の定期点検及び耐空検査など幅広くお客様の航空機の安全サポート致します。': 'We provide comprehensive safety support for your aircraft, including repairs, routine inspections, 50/100-hour periodic checks, and airworthiness inspections.',
    '点検': 'Inspection',
    '整備': 'Maintenance',
    '修理': 'Repair',
    '整備履歴': 'Maintenance History',
    '航空機の安全性と適切な運用を確保するためのプロセスです。点検は、航空機の機体、エンジン、システム、装備などの各部分の状態を評価し、問題や潜在的な故障を発見するために行われます。': 'This is the process of ensuring the safety and proper operation of aircraft. Inspections evaluate the condition of each component—including the airframe, engines, systems, and equipment in order to identify problems and potential failures.',
    '航空機整備士や整備スタッフによって行われます。航空機のメンテナンスマニュアルや運航規程に基づき、定められた手順や基準に従って整備を実施します。': 'Carried out by certified aircraft maintenance engineers and technicians. Maintenance is performed in accordance with established procedures and standards set out in the aircraft maintenance manual and operating regulations.',
    '機体、エンジン、システム、装備などの各部分の問題を特定し、必要な修復作業や部品の交換を行います。修理作業は安全性と規制要件に厳密に準拠する必要があります。航空機の履歴と安全性の評価に役立ちます。航空機の適切な状態と安全性を確保するために欠かせないもので航空機の修理は資格を持った専門家によって行われます。': 'Problems in the airframe, engines, systems, and equipment are identified, and the necessary restoration work and parts replacement are carried out. Repair work must strictly comply with safety and regulatory requirements. It helps assess the history and safety of the aircraft, and is essential for maintaining proper condition. All aircraft repairs are performed by qualified specialists.',

    // ── 6. TRANSPORT ─────────────────────────────────────────────────────────────
    '輸送サービス': 'Transport Services',
    '故障した機体を現地で修理': 'On-Site Repairs for Grounded Aircrafts',
    'エアロラボに持ち帰り修理': 'Return to Aerolab for Repair',
    'フェリーフライト': 'Ferry Flight',
    '航空機の売買と海外フェリーフライトサポート': 'Aircraft Sales & Overseas Ferry Flight Support',
    'フェリーフライト例': 'Ferry Flight Example',
    '現地で機体にトラブルがあってもご安心ください。当社スタッフが現地まで赴き、修理やメンテナンスを行います。万が一、事故や重大な損傷が発生した場合は、機体を適切に評価し、コンテナ輸送による移送や修理にも対応いたします。': 'Rest assured if your aircraft encounters trouble on-site. Our staff will travel to the location to perform repairs and maintenance. In the event of an accident or serious damage, we will properly assess the aircraft and arrange container transport and repair as needed.',
    '現地で修理が難しい場合は、機体をその場で解体し、安全かつ迅速にエアロラボの格納庫へ輸送いたします。当社格納庫にて熟練スタッフが徹底的な修理と整備を行い、機体を最適な状態に復元いたしますのでご安心ください。': 'If repairs are not feasible on-site, we will disassemble the aircraft and transport it safely and swiftly to Aerolab\'s hangar. Our skilled technicians will carry out thorough repairs and maintenance to restore the aircraft to its optimal condition.',
    '他社には真似できない価格とスピードでフライトプランを作成し、海外から日本への輸入を実現いたします。ロシアを含む複雑な空域の通過手続きや各国で必要な許可の取得も、当社の専門スタッフが的確に対応します。また、税関手続きなどの煩雑な業務もすべて代行し、お客様の負担を最小限に抑えることをお約束します。エアロラボなら、最適なルートと安心のサービスで確実にお届けします。': 'We create flight plans at unmatched speed and cost, enabling seamless import of aircraft from overseas to Japan. Our specialists handle complex airspace transit procedures including Russia, and secure all necessary permits from foreign authorities. We also manage all customs-related paperwork to minimize the burden on our clients. With Aerolab, your aircraft will be delivered reliably via the optimal route with complete peace of mind.',
    '航空機を売りたいお客様、または購入したいお客様の機体を海外へフェリーすることも可能です。その際の手続きは、最速かつ最安で行います。': 'We can also ferry aircraft overseas for clients looking to sell or purchase an aircraft. All related procedures are handled in the fastest and most cost-effective manner possible.',

    // ── 7. REMODEL ───────────────────────────────────────────────────────────────
    '改造実績': 'Remodeling Work',
    'GARMIN社製G600 Systemへの換装': 'Upgrade to Garmin G600 System',
    '内装の改造(内装の作り変え)': 'Interior Remodeling',
    '特殊用途向けの改造(スカイダイビング用機体のシャッタードア取付)': 'Special Purpose Modification (Skydiving Shutter Door Installation)',
    'アビオニクスとしては電子統合計器への換装、無線機/航空管制用自動応答装置の換装などの実績があります。電子計器に換装するとパイロットの状況判断を助け、安全性/効率性も向上します。これらアビオニクスの換装は航空局からの認可を受けるための証明作業が多く、難しく日本での工事例は少ないです。ですが、当社では長年の経験、技術により認可を取得することができます。': 'We have experience in upgrades such as replacing analog instruments with integrated electronic displays and swapping out radio and transponder systems. Switching to electronic instruments enhances pilot situational awareness and improves both safety and efficiency. These avionics upgrades require extensive certification work for Civil Aviation Bureau approval and are rarely performed in Japan. However, our years of experience and technical expertise allow us to successfully obtain the required approvals.',
    '古くなったBaron 58型の内装の張り替えを実施しました。お客様のイメージに合わせて幅広く対応することができます。もちろん耐火性などの証明も取得し、航空局の認可を得ています。': 'We reupholstered the interior of an aging Baron 58 aircraft. We can accommodate a wide range of design preferences to match each client\'s vision. Naturally, we also obtained the necessary certifications including fire resistance testing, ensuring full Civil Aviation Bureau approval.',
    'スカイダイビングクラブが所有している機体がダイビングを実施する時の利便性増加のためにシャッタードアを装着し当社が設計、製造をし航空局の認可を得ることができます。': 'We designed and manufactured a shutter door for an aircraft owned by a skydiving club to improve convenience during jump operations. We successfully obtained Civil Aviation Bureau approval for the modification.',

    // ── 8. PAINT ─────────────────────────────────────────────────────────────────
    '塗装工程': 'Painting Process',
    '塗装結果': 'Paint Results',
    'デザインの決定': 'Design Finalization',
    'ペイントリムーブ': 'Paint Removal',
    '洗浄': 'Cleaning',
    'マスキング': 'Masking',
    'オーナー様と協議の上デザインを決定いたします。こちらで飛行機にあう塗装を提案することも可能です。': 'The design is finalized in consultation with the owner. We can also propose suitable paint schemes for the aircraft.',
    '薬剤を使い安全に機体より従来のペイントを落とします。ステッカーなども綺麗に取り外すことも可能です。': 'We safely strip the existing paint from the aircraft using chemical agents. Decals and stickers can also be cleanly removed.',
    '塗料の乗り良くしたりやスキンのダメージを判定するために洗浄をします。': 'The aircraft is cleaned to improve paint adhesion and to assess any skin damage.',
    '決定したデザインを塗装するためにマスキングをします。': 'Masking is applied to prepare for painting the finalized design.',
    'プライマーを塗り、防錆効果を高め、通常の塗料を塗ります。': 'A primer is applied to enhance corrosion resistance, followed by the topcoat paint.',

    // ── 9. OTHER ─────────────────────────────────────────────────────────────────
    '航空機部品': 'Aircraft Parts',
    '航空機': 'Aircraft',
    'パイロット派遣・技術支援・訓練サポート': 'Pilot Dispatch, Technical Support & Training',
    '航空機保険のご案内': 'Aircraft Insurance Guidance',
    'ニカドサービス': 'NiCad Battery Service',
    '航空機用機器・アクセサリー販売': 'Aircraft Equipment & Accessories',
    '第三者賠償責任': 'Third-Party Liability',
    '乗客賠償責任': 'Passenger Liability',
    '搭乗者傷害保険': 'Occupant Injury Insurance',
    '救援者費用等・包括保障特約': 'Rescue Costs & Comprehensive Coverage',
    '航空機の部品やオーバーホールサービスを見つけるのにお困りの際は、ぜひご相談ください。どんなに古くて廃盤になった部品でも、当社の広範なネットワークを駆使して、あなたのご要望にお応えいたします。安心してお任せください。': 'If you are having difficulty sourcing aircraft parts or overhaul services, please feel free to consult us. No matter how old or discontinued a part may be, we will leverage our extensive network to meet your needs. You can count on us.',
    '近年、新たに資格を持つ商用パイロットの雇用市場は改善していますが、それでもなお高い競争力を維持しています。パイロットをお探しのお客様とお客様の要件に合致するパイロットのマッチングをお手伝いし、航空機運用をサポートします。': 'In recent years, the job market for newly qualified commercial pilots has improved, though it remains highly competitive. We assist clients seeking pilots by matching them with candidates who meet their requirements and provide support for aircraft operations.',
    '航空機の使用目的やお客様のご要望に応じた様々な補償内容をご案内しております。保険の契約からその後の対応までの一貫したサポート体制により、万が一、事故等で航空機に損害が生じた場合、迅速に保険手続きを進めることができます。24時間365日体制で事故対応を行っております。航空機保険には、4つの条項と1つの代表的な特約があり、ご希望の補償内容に応じて組み合わせをお選びいただけます。': 'We offer a variety of coverage options tailored to the purpose of use and the needs of each customer. With consistent support from policy inception through claims handling, we can swiftly process insurance procedures in the event of an accident. Our team is available 24 hours a day, 365 days a year for emergency response. Aircraft insurance consists of four clauses and one representative special rider, which can be combined according to your desired coverage.',
    'NiCad（ニカド）バッテリーのメンテナンスサービスをご提供しています。NiCadバッテリーは航空機において非常に重要な役割を果たしますが、定期的な点検とメンテナンスが欠かせません。当社では、バッテリーの性能を最大限に引き出すための充電・放電サイクルテスト、リフレッシュサービスなど、NiCadバッテリーに関するあらゆるサポートを行っております。お客様の機体に最適な状態でバッテリーを維持できるよう、確かな技術でサポートいたします。': 'We provide maintenance services for NiCad (nickel-cadmium) batteries. NiCad batteries play a critical role in aircraft, and regular inspection and maintenance are essential. We offer comprehensive support including charge/discharge cycle testing and refresh services. Our skilled technicians ensure your aircraft\'s batteries remain in optimal condition.',
    '八尾空港にてパイロットショップを運営しています。パイロットが必要なものや、航空グッズなども豊富に取り揃えています。コーヒーや軽食もご用意していますので是非お立ち寄りください。': 'We operate a pilot shop at Yao Airport, stocking a wide selection of pilot essentials, aviation merchandise, and accessories. Coffee and light refreshments are also available so please stop by!',

    // ── 10. COMPANY ───────────────────────────────────────────────────────────────
    'ビジョン': 'Our Vision',
    '少年の頃からあこがれた空へ・・・。あなたのフライトへの思いを全力でサポートします。': 'Towards The Skies We Have Always Dreamed Of... We Will Fully Support Your Passion for Flight.',
    'ご挨拶': 'A Message from Us',
    '当社のサイトへご訪問、心より皆様に感謝申し上げます。': 'We sincerely thank all visitors for visiting our website.',
    '私たちエアロラボインターナショナルは、革新的な航空技術の開発とグローバルな航空産業の進化を目指しています。お客様にとって最高の製品とサービスを提供することを常に追求し、常に高品質な成果物をお届けすることを使命としています。': 'We at Aerolab International are committed to the development of innovative aviation technology and the advancement of the global aviation industry. We constantly strive to deliver the finest products and services to our customers, and consider it our mission to provide consistently high-quality results.',
    '私たちのチームは、優れた専門知識と経験を持つエンジニアやデザイナー、熱意に溢れた研究者たちで構成されています。国内外の航空技術の最新トレンドに常にアンテナを張り、最先端の技術と最高の品質基準を取り入れています。': 'Our team is made up of engineers, designers, and passionate researchers with outstanding expertise and experience. We constantly monitor the latest trends in aviation technology both domestically and internationally, incorporating cutting-edge techniques and the highest quality standards.',
    'また、私たちは協力と協働を重視しています。お客様とのパートナーシップを築き、一緒に課題に取り組みながら、共に成長していくことを願っています。私たちの成功は、お客様の成功と密接に結びついていると信じております。': 'We also place great importance on collaboration and teamwork. We aspire to build strong partnerships with our customers, tackle challenges together, and grow alongside them. We firmly believe that our success is inseparable from the success of those we serve.',
    '株式会社エアロラボインターナショナルは、航空産業の未来をリードし、より持続可能な社会への貢献を目指して努力を惜しまない所存です。今後も皆様に信頼される企業であり続けるために、努力と情熱をもって取り組んでまいります。': 'Aerolab International is committed to leading the future of the aviation industry and contributing to a more sustainable society. We will continue to work with dedication and passion to remain a company trusted by all.',
    '会社情報': 'Company Profile',
    '社 名': 'Company Name',
    '代表者': 'Representative',
    '社員数': 'Number of Employees',
    '創 立': 'Date Founded',
    '主な事業': 'Main Businesses',
    '本社所在地': 'Head Office',
    '株式会社エアロラボインターナショナル': 'Aerolab International Inc.',
    '鼓呂雲 健造': 'Kenzo Colon',
    '30名': '30',
    '2014年4月22日': 'April 22, 2014',
    '航空機の修繕・整備・販売': 'Aircraft Repair, Maintenance & Sales',
    '管理・輸送・輸出入': 'Management, Transport & Import/Export',
    'グッズ販売・企画': 'Merchandise Sales & Planning',
    'プロモーション動画': 'Promotional Video',

    // ── 11. ACHIEVEMENTS ──────────────────────────────────────────────────────────
    'アジア太平洋地域のトップMRO': 'Top MRO in APAC',
    '詳細はこちら': 'Learn More Here',
    'エアロラボは、Aerospace & Defense Reviewにより、アジア太平洋地域のトップMRO（整備、修理、オーバーホール）プロバイダーとして認定されました。この名誉ある認定は、私たちの卓越した技術力、最先端の技術、そしてお客様に最高品質のサービスを提供するという扇るぎないコミットメントを証明しています。航空業界における信頼できるパートナーとして、エアロラボは、航空機の整備において総合的で効率的、かつ信頼性の高いソリューションを提供し、安全性と最適なパフォーマンスを確保しています。業界をリードする専門知識と優れたサービスで、エアロラボはアジア太平洋地域のMROサービスのスタンダードを築き続けています。どこへでもお客様の航空機を最高の状態で保つため、ぜひ私たちにお任せください。': 'Aerolab has been recognized by Aerospace & Defense Review as a top MRO (Maintenance, Repair, and Overhaul) provider in the Asia Pacific region. This prestigious recognition demonstrates our exceptional technical capabilities, cutting-edge technology, and unwavering commitment to delivering the highest quality services to our customers. As a trusted partner in the aviation industry, Aerolab provides comprehensive, efficient, and reliable solutions for aircraft maintenance, ensuring safety and optimal performance. With industry-leading expertise and outstanding service, Aerolab continues to set the standard for MRO services across the Asia Pacific region. Trust us to keep your aircraft in peak condition, wherever you are.',
    'Newsweek掲載': 'Featured in Newsweek',
    '国際誌「Newsweek」にて当社インタビューが掲載': 'Our Interview Featured in International Magazine Newsweek',
    'このたび当社は、国際ニュース詌「Newsweek」よりインタビューの機会をいただき、当社の事業内容やこれまでの実績、航空分野における専門性についてご紹介いただきました。本掲載は、当社の取り組みおよび実績が評価されたものと認識しております。今後もグローバルな視点と専門性をもとに、品質および信頼性のさらなる向上に努めてまいります。': 'We were recently honored to be interviewed by the international news magazine Newsweek, which featured our business activities, track record, and expertise in the aviation field. We recognize this publication as an acknowledgment of our efforts and achievements. Going forward, we will continue to strive for further improvements in quality and reliability based on our global perspective and specialized knowledge.',
    '認定ディーラー': 'Authorized Dealer',
    'GARMINアビオニクスの認定ディーラー': 'Authorized Garmin Avionics Dealer',
    'エアロラボはGarminアビオニクスの正規ディーラーとして、新品、オーバーホール済み、修理済みのアビオニクス機器を業界最安値でご提供しています。また、システムのアップグレードを検討されている方には、アビオニクス全体をゼロからリモデリングするサービスも対応可能です。さらに、2020年にはGarmin社よりシルバーアワードを受賞し、世界販売上位15%にランクインしました。この実績は、エアロラボのサービス品質とお客様からの信頼の証です。': 'As an authorized Garmin avionics dealer, Aerolab offers new, overhauled, and repaired avionics equipment at the industry\'s best prices. For those considering a system upgrade, we also offer full avionics remodeling services from scratch. In 2020, we received the Silver Award from Garmin and ranked in the top 15% of global sales, a testament to the quality of our service and the trust our customers place in us.',
    'YS-11保存プロジェクト': 'YS-11 Preservation Project',
    'プロジェクト概要': 'Project Overview',
    '2014年12月、エアロラボは国土交通省航空局が所有していた最後のYS-11（機体番号JA8709）を一般競争入札で223万200円で落札しました。このプロジェクトは、機体の整備を行い、再び空へ飛び立たせることを目指したものです。日本の航空法規制への適合を考慮し、機体記号を日本国籍「JA8709」から米国籍「N462AL」へ変更して登録、2015年3月にはエンジンの始動に成功し、塗装の変更を含む整備もほぼ完了しました。同年5月24日、連邦航空局（FAA）から飛行許可を取得し、5月27日に東京国際空港を離陸。高松空港を経由した後、最終的に能登空港隣接の日本航空学園で保管されています。': 'In December 2014, Aerolab acquired the last YS-11 aircraft owned by the Civil Aviation Bureau of the Ministry of Land, Infrastructure, Transport and Tourism (registration JA8709) through a public competitive bid for 2,230,200 yen. The project aimed to restore and return the aircraft to flight. Taking into account compliance with Japanese aviation regulations, the registration was changed from Japanese nationality "JA8709" to US nationality "N462AL." Engine start-up was successfully completed in March 2015, and maintenance including a paint change was nearly finished. On May 24 of the same year, a flight permit was obtained from the Federal Aviation Administration (FAA), and the aircraft departed Tokyo International Airport on May 27. After a stop at Takamatsu Airport, it is now stored at the Japan Aviation Academy adjacent to Noto Airport.',
    'YS-11の歴史的価値': 'Historical Significance of the YS-11',
    'YS-11は日本が初めて独自開発した旅客機であり、日本航空産業の象徴的な存在です。この機体を保護し、未来に伝えることは、技術的な進歩や航空史の理解を深めるだけでなく、日本が築いた航空イノベーションの足跡を次世代に残すことに繋がります。エアロラボは、YS-11の保存を通じて日本の航空産業の歴史的意義を未来に伝える役割を担っています。': 'The YS-11 was Japan\'s first independently developed passenger aircraft and stands as a symbol of the Japanese aviation industry. Preserving this aircraft and passing it on to future generations not only deepens our understanding of technological progress and aviation history, but also ensures that the legacy of Japan\'s aviation innovations is carried forward to the next generation. Aerolab is proud to play a role in conveying the historical significance of Japan\'s aviation industry through the preservation of the YS-11.',

    // ── 12. INVESTMENT ────────────────────────────────────────────────────────────
    '開示情報一覧': 'Disclosure Information',
    'PDFファイルをご覧になるためには最新のAdobe Acrobat Readerが必要となります。Adobe Acrobat Readerはアドビシステムズのサイトより無償でダウンロードできます。': 'The latest Adobe Acrobat Reader is required to view PDF files. Adobe Acrobat Reader can be downloaded free of charge from the Adobe Systems website.',
    '公告': 'Public Announcements',
    '電子公告': 'Electronic Announcements',
    '決算公告': 'Financial Announcements',
    'ディスクロージャーポリシー': 'Disclosure Policy',
    '1.情報開示の基準': '1. Standards for Information Disclosure',
    '当社は、金融商品取引法等の諸法令および東京証券取引所の定める有価証券上場規程の「会社情報の適時開示等」(以下、「適時開示規則」といいます)に従って、透明性、公平性、継続性を基本とした迅速な情報開示を行います。また諸法令や適時開示規則に該当しない場合でも、株主や投賄家の皆様に当社を理解いただくために重要あるいは有益であると判断した情報につきましては、積極的かつ公平に開示します。なお、個人情報、顧客情報、および関係者の権利を侵害することになる情報につきましては開示しません。': 'In accordance with financial instruments and exchange laws and the timely disclosure rules set forth by the Tokyo Stock Exchange, we disclose information promptly based on the principles of transparency, fairness, and continuity. Even for matters not covered by these rules, we proactively and fairly disclose information deemed important or useful for shareholders and investors. We do not disclose personal information, customer information, or information that would infringe upon the rights of related parties.',
    '2.情報開示の方法': '2. Methods of Information Disclosure',
    '適時開示規則の定める情報の開示は、同規則に従い東京証券取引所の提供する適時開示情報伝達システム(TDnet)を通じて行うとともに、同システムにより公開した後は、速やかに当社ホームページにも掲載します。適時開示規則に該当しない情報につきましても、重要あるいは有益であると判断した情報につきましては、当社ホームページへの掲載等により広く開示します。': 'Information subject to timely disclosure rules is released through the Tokyo Stock Exchange\'s Timely Disclosure Network (TDnet) in accordance with those rules, and is also promptly posted on our website. Information not subject to the timely disclosure rules but deemed important or useful is also widely disclosed through our website and other means.',
    '3.インサイダー取引の未然防止': '3. Prevention of Insider Trading',
    'インサイダー取引の防止等につきましては、情報管理規程ならびにインサイダー取引管理規程を制定しその防止を図っております。また、毎年、役員・従業員を対象にインサイダー取引規制に関する勉強会を開催する他、解説書を配布するなどし、その趣旨の周知徹底と理解啓蒙に努めるとともに、適宜、社内通達にてインサイダー取引に関する注意を喚起しています。': 'To prevent insider trading, we have established information management regulations and insider trading control regulations. We also hold annual seminars for directors and employees on insider trading regulations, distribute explanatory materials, and issue internal notices to ensure thorough awareness and understanding of the relevant rules.',
    '4.業績予想および将来情報の取り扱い': '4. Handling of Financial Forecasts and Forward-Looking Information',
    '当社が開示する業績予想、将来の見通し、戦略、目標等のうち、過去または現在の事実に関するもの以外は将来の見通しに関する記述であり、これらは、当社が現時点で入手している情報および合理的であると判断される一定の前提に基づく計画、期待、判断を根拠としております。したがって、実際の業績等は、経済情勢等様々な不確定要素の変動要因によって、開示した業績予想等と異なる結果になる可能性があります。': 'Among the financial forecasts, outlooks, strategies, and targets we disclose, those not relating to past or present facts constitute forward-looking statements. These are based on plans, expectations, and judgments grounded in information available at the time and certain assumptions deemed reasonable. Accordingly, actual results may differ from disclosed forecasts due to various uncertain factors such as economic conditions.',
    '5.沈黙期間': '5. Silent Period',
    '当社は、決算情報(半期決算情報を含む)の漏洩を防ぎ、かつ情報開示の公平性を確保する観点から、決算(半期決算)期末日の翌日から各決算発表日までを沈黙期間と定めております。この期間中は、決算・業績見通しに関する質問への回答やコメントを差し控えることとしております。ただし、この期間中に業績予想が大きく変動する見込が出てきた場合には、適時開示規則に従い、適宜公表することとしております。': 'In order to prevent leakage of financial information (including interim results) and to ensure fairness in disclosure, we designate a silent period from the day after the fiscal (or interim) period end through each earnings announcement date. During this period, we refrain from answering questions or commenting on financial results and performance outlooks. However, if a significant change in financial forecasts becomes likely during this period, we will make appropriate disclosures in accordance with timely disclosure rules.',
    '6.社内体制の整備について': '6. Development of Internal Systems',
    '当社は本ディスクロージャーポリシーに則り、諸法令や適時開示規則に従った適切な情報開示を行うために、社内体制の整備・充実に努めております。': 'In accordance with this Disclosure Policy, we are working to strengthen and improve our internal systems to ensure appropriate disclosure of information in compliance with applicable laws and timely disclosure rules.',
    '当ウェブサイトに掲載されている当社の業績見通し、計画、戦略などは、現時点で入手可能な情報に基づき当社の経営者が判断した、将来の業績に関係する見通しであり、リスクや不確実性を含んでいます。また、当社の事業をとりまく、経済情勢、市場の動向等の様々な重要な要素により、実際の業績は、業績予想とは、異なり得ることを予めご承知おきください。': 'The financial outlooks, plans, and strategies posted on this website are forward-looking statements based on management\'s judgment using information available at the time, and involve risks and uncertainties. Please be aware in advance that actual results may differ from forecasted performance due to various important factors surrounding our business, including economic conditions and market trends.',
    '当ウェブサイトのいかなる情報も、当社の株式の購入や売却等を勧誘するものではありません。': 'None of the information on this website constitutes a solicitation to purchase or sell shares of our company.',
    '投資に関する決定は利用者ご自身の判断でなさるようお願いいたします。': 'Investment decisions should be made at the sole discretion of the user.',
    '当ウェブサイトに掲載された情報は予告なく変更や掲載を取りやめることがあります。また、通信環境やお客様のコンピュータの状況、その他の理由により当ウェブサイトを正常に利用できない場合があります。': 'Information posted on this website is subject to change or removal without prior notice. In addition, the website may not function properly due to network conditions, your computer environment, or other reasons.',
    '当ウェブサイトの内容について、当社は万全を期して掲載しておりますが、掲載された情報に誤りがあった場合や第三者によるデータの改ざん等があった場合、またデータのダウンロード等によって生じた障害及び損害については、当社は一切責任を負うものではありませんのであらかじめご了承ください。': 'While we take every care to ensure the accuracy of information on this website, we accept no responsibility for any errors in posted information, unauthorized alteration by third parties, or any damage or loss arising from downloading data. Please be aware of this in advance.',
    'IRについてのお問合せ': 'IR Inquiries',
    'ウェブサイトからの相談窓口': 'Online Inquiry',
    'メールアドレス：': 'Email Address：',
    'お電話での相談窓口': 'Phone Inquiry',
    '電話番号：072-990-1232 (平日10:00~17:00、祈日・年末年始を除く)': 'Tel： +81 72-990-1232 (Weekdays 10:00–17:00 Except Holidays)',
    'Tel：072-990-1232': 'Tel：+81 72-990-1232',
    'Fax：072-990-1338': 'Fax：+81 72-990-1338',
    '上場記念動画': 'Listing Commemorative Video',
    '決算短信': 'Financial Results',
    '有価証券報告書': 'Annual Securities Report',
    '四半期報告書': 'Quarterly Report',
    '適時開示情報': 'Timely Disclosure',
    '適時開示': 'Timely Disclosure',
    'プレスリリース': 'Press Release',
    '総会資料': 'Shareholder Meeting Materials',
    '発行者情報': 'Issuer Information',
    'IR資料': 'IR Materials',
    'お知らせ': 'Notices',
    '全て': 'All',
    '年を選択してください': 'Select Year',
    '2026年': '2026',
    '2025年': '2025',
    '2024年': '2024',
    '2023年': '2023',
    '2022年': '2022',
    '2021年': '2021',
    '2020年': '2020',
    '2024年度': 'FY2024',
    '2023年度': 'FY2023',
    '2022年度': 'FY2022',
    '2021年度': 'FY2021',
    '2020年度': 'FY2020',
    '2019年度': 'FY2019',

    // ── 13. RECRUITMENT ───────────────────────────────────────────────────────────
    '航空整備士募集中のお知らせ': 'Aircraft Maintenance Technician',
    '【仕事内容】': 'Job Description',
    '【必須資格】': 'Required Qualifications',
    '【勤務時間】': 'Work Hours',
    '【勤務地】': 'Work Location',
    '【雇用形態】': 'Employment Type',
    '【ご連絡先】': 'Contact',
    '当社の求人情報をご覧いただきありがとうございます。現在募集中のポジションは下記に掲載されています。': 'Thank you for your interest in our job listings. Currently open positions are listed below.',
    'ドック整備': 'Hangar Maintenance',
    '◎ チェックリストに沿って、機体や各パーツの取り付け部分、ケーブルなどに異常が無いか確認': '◎ Inspect aircraft structures, part attachment points, cables, and systems according to checklists',
    'ショップ整備': 'Shop Maintenance',
    '◎ エンジンや電装部品、油圧系統の部品を取り外してチェック': '◎ Remove and inspect engine components, electrical parts, and hydraulic system components',
    '加工・改造': 'Machining & Modifications',
    '◎ 塗装や計器盤などの加工や取り付け': '◎ Machining and installation of paint systems, instrument panels, and other components',
    '機体の受け入れ・発送': 'Aircraft Reception & Shipping',
    '◎ パーツごとに分解された機体の組み立て': '◎ Assembly of aircraft disassembled into individual parts',
    '◎ 海外へ輸送するための解体、梱包作業': '◎ Disassembly and packaging for overseas transport',
    '一等または二等航空整備士をお持ちの方': 'First or Second Class Aircraft Maintenance Technician certification required',
    '一等または二等航空運航整備士をお持ちの方': 'First or Second Class Aircraft Operations Maintenance Technician certification required',
    'プライベートジェットの整備経験は不問、学歴不問': 'Private jet maintenance experience not required; no educational restrictions',
    '9:00～18:00 (所定労働時間8時間/休憓60分)': '9:00–18:00 (8 hours scheduled work / 60-minute break)',
    '八尾空港(大阪府) 転勤無し/マイカー通勤OK': 'Yao Airport (Osaka) — No relocation required / Commuting by personal vehicle OK',
    '正社員 (試用期間  3カ月)': 'Full-time Employee (3-month probationary period)',
    '◎ 期間中も、給与等待遇は本採用時と変わりありません。': '◎ Salary and benefits during the probationary period are the same as regular employment.',
    'こんな方を求めています': 'We Are Looking For...',
    '◎ 需要のある業界で長く活躍したい方': '◎ Those who want a long-term career in a high-demand industry',
    '◎ 飛行機の全てを知りたい方': '◎ Those who want to know everything about aircraft',
    '◎ これまで以上のスキルを身につけたい方': '◎ Those who want to develop skills beyond their current level',
    '◎ もっと飛行機に触れて整備経験を積みたい方': '◎ Those who want more hands-on aircraft experience and to build their maintenance skills',
    '◎ 関西エリアで働きたい方': '◎ Those who want to work in the Kansai area',
    '採用担当までお問い合わせください。': 'Please contact our recruitment team.',
    '受付時間:月~金/9:00～18:00': 'Reception Hours: Mon–Fri / 9:00–18:00',

    // ── 14. SECURITY POLICY ───────────────────────────────────────────────────────
    '株式会社エアロラボインターナショナルは、企業理念を実現するためには、お客様の信頼を得ることを第一と考え、ここに「情報セキュリティ基本方針」を定め、下記事項を常に念頭に置き、経営陣を含め全従業員に周知徹底し、この方針に従い適切な情報資産の保護に努めてまいります。': 'Aerolab International Inc. considers earning the trust of our customers to be the foundation for fulfilling our corporate philosophy. We hereby establish this "Information Security Policy," keep the following items in mind at all times, ensure that all employees including management are fully informed, and strive to protect our information assets appropriately in accordance with this policy.',
    '実施事項': 'Implementation Items',
    '顧客情報の保護を通じて、顧客との信頼関係を強固なものとします。': 'We strengthen trust relationships with customers through the protection of customer information.',
    '社訓及び経営理念、法令遵守を通じて、企業としての社会的責任を果たすものとします。': 'We fulfill our corporate social responsibilities through adherence to our company motto, management philosophy, and legal compliance.',
    '情報セキュリティの教育・訓練を従業員に対して定期的に実施します。': 'We regularly conduct information security education and training for employees.',
    '情報セキュリティの事故・違反等があった場合は、速やかに対応します。': 'In the event of an information security incident or violation, we respond promptly.',
    '情報セキュリティ目的を設定し、実施し、維持します。': 'We establish, implement, and maintain information security objectives.',
    '情報セキュリティに関連する適用される要求事項を満します。': 'We comply with all applicable requirements related to information security.',
    '責任と義務及び罰則': 'Responsibilities, Obligations, and Penalties',
    '基本方針を維持するために策定された手順に従い、情報セキュリティに対する事故及び弱点を報告する責任を有し、当社が取扱うすべての情報資産の保護を危うくする行為を行なった者は、就業規則および法令等に従い処分を行ないます。': 'In accordance with procedures established to uphold this policy, individuals have a responsibility to report information security incidents and vulnerabilities. Those who engage in acts that jeopardize the protection of all information assets handled by our company will be subject to disciplinary action in accordance with work regulations and applicable laws.',
    '定期的な見直し': 'Periodic Review',
    '情報セキュリティマネジメントシステムは、定期的に遵守状況を点検・見直し、社会や社内の環境変化に応じて、継続的改善に努めます。': 'The information security management system shall be regularly reviewed for compliance and shall strive for continuous improvement in response to changes in the social and internal environment.',
    '制定日：2022年1月1日': 'Effective Date: January 1, 2022',

    // ── 15. CONTACT ───────────────────────────────────────────────────────────────
    'お問い合わせ先': 'Contact Information',
    'お問い合わせ内容に応じて、以下の担当窓口よりご連絡ください。': 'Please contact the appropriate department below based on the nature of your inquiry.',
    '総合お問い合わせ': 'General Inquiry',
    '一般的なお問い合わせや会社情報に関するご質問、各部署に該当しない内容はこちらへご連絡ください。': 'For general inquiries, questions about company information, or matters not covered by other departments, please contact us here.',
    '整備サポート': 'Maintenance Support',
    '航空機整備、技術サポート、各種点検およびメンテナンスに関するお問い合わせはこちらへご連絡ください。': 'For inquiries regarding aircraft maintenance, technical support, inspections, and maintenance services, please contact us here.',
    '運航サポート': 'Flight Operations Support',
    'フライトオペレーション、スケジューリング、許可申請、ハンドリングおよび運航手配に関するお問い合わせはこちらへご連絡ください。': 'For inquiries regarding flight operations, scheduling, permit applications, handling, and flight arrangements, please contact us here.',
    '部品サポート': 'Parts Support',
    '航空機部品の調達、在庫確認、見積依頼など部品関連のお問い合わせはこちらへご連絡ください。': 'For inquiries regarding aircraft parts procurement, inventory checks, quote requests, and other parts-related matters, please contact us here.',
    '売買・コンサルティング': 'Sales & Consulting',
    '航空機の売買、取得、ブローカレッジサービスおよびマーケットに関するご相談はこちらへご連絡ください。': 'For inquiries regarding aircraft sales, acquisition, brokerage services, and market consultations, please contact us here.',
    'エアロラボコリア': 'Aerolab Korea',
    '韓国拠点に関するお問い合わせや、韓国国内での各種サービスに関するご相談はこちらへご連絡ください。': 'For inquiries about our Korea office or services provided within Korea, please contact us here.',
    'パイロットショップの商品（食品・グッズ・雑貨）に関するお問い合わせやご注文についてはこちらへご連絡ください。': 'For inquiries or orders regarding Pilot Shop products (food, goods, and merchandise), please contact us here.',
    '拠点情報': 'Office Locations',
    '住所': 'Address',
    '〒581-0043　大阪府八尾市空港2-12': '2-12 Kuko, Yao City,\nOsaka, Japan 581-0043',
    '電話番号': 'Phone',
    'FAX番号': 'Fax',
    '9：00〜18：00': '9:00 – 18:00',
    '営業時間': 'Business Hours',
    '営業日': 'Operating Days',
    '年中無休': 'Open Year-Round',
    '不定休': 'Irregular Holidays',

    // ── 16. 404 ───────────────────────────────────────────────────────────────────
    // (404 heading paragraph is in section 3 PAGE HEADINGS above)

    // ── 17. AIRCRAFT SPECS MAIN PAGE ──────────────────────────────────────────────
    '世界をリードする航空機メーカーの機体仕様や性能データをご覧いただけます。各航空機の特徴や運用性能を分かりやすく整理し、幅広い情報を掲載。ビジネスジェットをはじめ、多様な機体の比較・検討にもご活用いただけます。': 'Browse specifications and performance data from the world\'s leading aircraft manufacturers. Organized for clarity, covering the key features and operational capabilities of each aircraft. Ideal for comparing and evaluating a wide range of aircraft, from business jets to specialized models.',
    'お探しの航空機はお決まりですか？以下に入力して、該当ページへ直接移動できます。': 'Looking for a specific aircraft? Enter it below to navigate directly to its page.',
    '航空機タイプ別検索': 'Browse by Aircraft Type',
    '航空機タイプを選択し、各機体の仕様や性能データをご覧いただけます。': 'Select an aircraft type to view specifications and performance data for each model.',
    '洗練されたキャビン空間と優れた航続性能により、上質で効率的な移動を実現します。ビジネスからプライベートまで、時間価値を重視する多様なニーズに応える航空機です。': 'Refined cabin spaces and exceptional range performance deliver a premium, efficient travel experience. Designed for a wide range of needs — from business travel to private journeys — these aircraft cater to those who value their time.',
    '高い経済性と優れた短距離運航性能を備え、地域間移動に適した航空機です。多様な運航環境に対応し、実用性と信頼性を兼ね備えた柔軟な運用を可能にします。': 'Highly economical with outstanding short-field performance, turboprop aircraft are well-suited for regional travel. Versatile and reliable, they offer flexible operations across a wide range of environments.',
    '軽快な操縦性と高い汎用性を備え、幅広い用途で活躍する航空機です。訓練飛行から個人利用まで、多彩なシーンに対応する身近なエアモビリティを提供します。': 'Agile and highly versatile, piston aircraft excel across a wide variety of applications. From training flights to personal use, they provide accessible air mobility for countless situations.',
    '回転翼機・ヘリコプター': 'Rotorcraft & Helicopters',
    '優れた機動性と離着陸性能により、目的地へスムーズかつ効率的な移動を実現します。都市部から自然豊かなエリアまで幅広い環境に対応し、自由度の高い空の移動を可能にします。': 'Exceptional maneuverability and landing flexibility enable smooth, efficient travel to virtually any destination. From urban centers to remote natural environments, rotorcraft provide unmatched freedom of movement.',
    '収録情報': 'What\'s Included',
    'データベースについて': 'About The Database',        
    '機体性能比較': 'Performance Comparison',
    '主要性能データを視覚的に比較し、各機体の特性を分かりやすく把握できます。': 'Visually compare key performance data to quickly understand the characteristics of each aircraft.',
    '寸法・重量・搭載容量など、各機体の詳細な技術仕様を掲載しています。': 'Detailed technical specifications for each aircraft, including dimensions, weights, and payload capacity.',
    '速度・航続距離・燃料消費率など、運用性能を示す主要データを掲載しています。': 'Key operational performance data including speed, range, and fuel consumption rates.',
    '外観やキャビンを高品質な写真と図表で掲載し、機体の魅力を視覚的にご覧いただけます。': 'High-quality photographs and diagrams of exteriors and cabin interiors to visually showcase each aircraft.',
    '当社の航空機仕様データベースでは、世界の多彩な航空機に関する最新情報を掲載しています。各機体の技術仕様や性能データをはじめ、キャビン空間や運用特性まで、選定に役立つ情報を分かりやすく整理しています。ビジネスジェットから希少性の高い機体まで、上質な空の移動を求めるお客様に向けた情報資料としてご活用いただけます。': 'Our aircraft specifications database provides up-to-date information on a wide variety of aircraft from around the world. Technical specs, performance data, cabin details, and operational characteristics are all organized for easy reference. From business jets to rare and unique aircraft, this resource is designed for those seeking premium air travel.',
    // Also used on the old Aircraft Specs page variant
    '航空機検索': 'Aircraft Search',
    '仕様データベース': 'Specifications Database',
    '航空機仕様データベース': 'Aircraft Specifications Database',
    '航空機を検索...': 'Search Aircrafts...',
    'ビジネスジェット': 'Business Jet',
    'ターボプロップ機': 'TurboProp Aircraft',
    'ピストン機': 'Piston Aircraft',
    '回転翼機': 'Rotorcraft',
    'ヘリコプター': 'Helicopters',
    '詳細仕様': 'Detailed Specifications',
    '性能指標': 'Performance Metrics',
    '高品質画像': 'High-Quality Images',

    // ── 18. BUSINESS JET TYPE PAGE ────────────────────────────────────────────────
    'ビジネスジェットは、少人数での移動に特化した航空機です。快適性と機動性を兼ね備え、短距離移動に適した軽量機から、大陸間飛行に対応する超長距離機まで幅広い機種が存在します。高い柔軟性とプライバシー性に加え、移動時間の効率化を実現できることも大きな特徴です。また、定期航空便では利用が難しい空港へのアクセスが可能なため、目的地や運航計画に応じた自由度の高い移動を提供します。': 'Business jets are aircraft designed for small-group travel, combining comfort and agility. The category spans a wide range — from light jets suited for short hops to ultra-long-range aircraft capable of intercontinental flights. High flexibility, privacy, and the ability to save travel time are hallmarks of business aviation. Access to airports unavailable to commercial airlines adds further freedom when planning routes and destinations.',
    '超長距離ビジネスジェット': 'Ultra Long-Range Business Jet',
    '詳細': 'Details',
    '最大航続距離': 'Max Range',
    '最大速度': 'Max Speed',
    '最大乗客数': 'Max Passengers',

    // ── 19. G550 PAGE ─────────────────────────────────────────────────────────────

    // Metadata / hero
    'ガルフストリーム G550': 'Gulfstream G550',

    // Summary section
    '概要': 'Summary',
    '高速巡航時の速度': 'Cruise Speed',
    '最大搭乗人数': 'Maximum Passengers',
    '標準構成 13-16名': 'Standard Config: 13–16',
    '6,750海里': '6,750 NM',
    'マッハ0.85': 'Mach 0.85',
    '19名': '19',

    // Summary description paragraph
    'ガルフストリーム G550は2003年から2021年にかけて製造された超長距離ビジネスジェットで、2名乗務体制により運航され、最大19名の乗客搭乗が可能です。最大運用高度は': 'The Gulfstream G550, manufactured from 2003 to 2021, is an ultra long-range business jet operated by a two-pilot crew with a maximum seating capacity of 19 passengers. Maximum operating altitude: ',
    '、高速巡航速度はマッハ0.85 (488 kts / ': '; high-speed cruise: Mach 0.85 (488 kts / ',
    ')、最大航続距離は約': '); maximum range approximately ',
    '（6,750海里）です。': ' (6,750 NM).',

    // Cost analysis
    'コスト分析': 'Cost Analysis',
    '運航コストの内訳': 'Operating Cost Breakdown',
    '条件を設定': 'Configure Parameters',
    '年間飛行時間': 'Annual Flight Hours',
    '表示通貨': 'Display Currency',
    '更新': 'Update',
    '表示単位': 'Unit System',
    '年間変動費': 'Annual Variable Cost',
    '年間変動費合計': 'Total Annual Variable Cost',
    '年間固定費': 'Annual Fixed Cost',
    '年間総コスト(固定費＋変動費)': 'Total Annual Cost',
    '月間総コスト(固定費＋変動費)': 'Total Monthly Cost',
    '時間当たりコスト': 'Cost per Flight Hour',
    '時間変動費': 'Hourly Variable Cost',
    '燃料費': 'Fuel Cost',
    '整備関連費用': 'Airframe Maintenance',
    'エンジン・APU整備プログラム費': 'Engine & APU Maintenance Program',
    '時間変動費合計': 'Total Hourly Variable Costs',
    '年間固定費明細': 'Annual Fixed Cost',
    '乗員人件費 (給与・福利厚生)': 'Crew Compensation (Salary & Benefits)',
    '乗組員訓練': 'Crew Training',
    '乗員訓練費': 'Crew Training',
    '格納庫': 'Hangar',
    '格納庫費': 'Hangar Fees',
    '保険': 'Insurance',
    '航空機保険料': 'Aircraft Insurance',
    'その他固定費': 'Miscellaneous Fixed',
    '管理費': 'Management Fees',
    '年間固定費合計': 'Total Annual Fixed Costs',
    '変動費の構成': 'Variable Cost Breakdown',
    '固定費の構成': 'Fixed Cost Breakdown',

    // Chart labels (shared with cost charts)
    '燃料': 'Fuel',
    '機体整備': 'Airframe Maintenance',
    'エンジン・APU整備': 'Engine/APU Maintenance',
    'その他変動費': 'Other Variable Costs',
    '乗組員給与・福利厚生': 'Crew Salary & Benefits',
    '管理': 'Management',

    // Performance section
    '性能': 'Performance',
    '飛行速度': 'Flight Speed',
    '最大速度': 'Max Speed',
    '長距離巡航': 'Long-Range Cruise',
    '長距離巡航時の速度': 'Long-Range Cruise Speed',
    '航続距離と飛行高度': 'Range & Altitude',
    '最大航続距離': 'Max Range',
    '航続距離 (マッハ0.8、乗員4名・乗客8名の場合)': 'Range (Mach 0.8, 4 Crew + 8 Passengers)',
    '無給油最大航続距離 (乗客なし)': 'Max Non-Stop Range (No Passengers)',
    '上昇限界': 'Service Ceiling',
    '巡航開始高度': 'Initial Cruise Altitude',
    '重量仕様': 'Weight Specifications',
    '最大離陸重量': 'Max Takeoff Weight',
    '最大着陸重量': 'Max Landing Weight',
    '基本運航重量 (乗員4人)': 'Basic Operating Weight (4 Crew)',
    '最大搭載量': 'Maximum Payload',
    '最大燃料搭載時の有効搭載量': 'Payload at Max Fuel',
    '最大無燃料重量': 'Max Zero Fuel Weight',
    '燃料消費': 'Fuel Consumption',
    '燃料消費量': 'Fuel Consumption',
    '時間あたり燃料使用量': 'Fuel Usage Per Hour',
    '総燃料容量': 'Total Fuel Capacity',
    '燃料重量': 'Fuel Weight',
    '滑走距離要件': 'Runway Requirements',
    'メートル': 'Meters',
    'フィート': 'Feet',
    '最短離陸距離': 'Minimum Takeoff Distance',
    '最短着陸距離（PART 91）': 'Minimum Landing Distance (PART 91)',
    '最短着陸距離（PART 135）': 'Minimum Landing Distance (PART 135)',
    '滑走路の測定値は、晴天・乾燥した滑走路を基準とした最短値です。距離は乗客の体重、手荷物の重量、風、滑走路の状態、気温、空港の標高によって変わる場合があります。': 'The runway measurements are the minimum values based on a clear day and dry runway. The distance may change depending on passenger weights, baggage weight, winds, runway conditions, temperature and airport elevation.',
    '距離': 'Distance',

    // Range map section
    'インタラクティブ航続距離マップ': 'Interactive Range Map',
    '出発空港を検索：': 'Search Departure Airport:',
    '空港名またはコードで検索（例：東京またはHND）...': 'Search by airport name or code (e.g., Tokyo or HND)...',
    '空港を検索・選択し、その地点からのG550の航続距離を確認できます。': 'Search and select an airport to view the G550\'s range from that location.',
    '航続距離 6,750海里': 'Range: 6,750 NM',
    '満席時航続距離(19名) 4,200海里': 'Full-Pax Range (19 Pax): 4,200 NM',
    '青いレンジリングは、ガルフストリーム社公表の航続距離です。これは乗客8名＋乗員4名、かつ良好な風・気象条件を前提としています。乗客が増えると最大ペイロードを超えるため、追加搭乗には燃料を減らす必要があります。': 'The blue range ring represents the range published by Gulfstream. This assumes 8 passengers and 4 crew under favorable wind and weather conditions. As passenger count increases beyond the maximum payload, fuel must be reduced to accommodate additional occupants.',
    '最大の19名搭乗時には、重量に対応するため大幅な燃料削減が必要です。赤いレンジリングはその際の平均的な目安ですが、実際の航続距離は天候や風の影響で増減します。': 'At full capacity of 19 passengers, a significant fuel reduction is required to manage the weight. The red range ring provides an average estimate for this configuration; actual range will vary with weather and wind conditions.',

    // Interior / cabin section
    '設計': 'Design',
    'キャビン': 'Cabin',
    '席配置': 'Seating Configuration',
    '標準構成': 'Typical Configuration',
    '最小乗組員': 'Minimum Crew',
    '最小乗組員 (パイロット)': 'Minimum Flight Crew (Pilots)',
    '客室乗務員': 'Flight Attendants',
    '客室乗務員 (任意)': 'Cabin Crew (Optional)',
    'キャビン寸法': 'Cabin Dimensions',
    'キャビン高': 'Cabin Height',
    'キャビン幅': 'Cabin Width',
    '客室の広さ (容積)': 'Cabin Volume',
    'キャビン長 (荷物室含む)': 'Cabin Length (incl. baggage)',
    '荷物室容積': 'Baggage Volume',

    // Exterior section
    '外装寸法': 'Exterior Dimensions',
    '機体外観': 'Exterior',
    '全長': 'Overall Length',
    '全幅': 'Wingspan',
    '全高': 'Overall Height',

    // Engine & APU section
    'エンジン': 'Engines',
    'モデル': 'Model',
    'ロールスロイス製BR710-C4-11': 'Rolls-Royce BR710-C4-11',
    '補助動力装置 (APU)': 'Auxiliary Power Unit (APU)',
    '離陸推力 (2x)': 'Takeoff Thrust (2x)',

    // Section labels shared across interior/exterior/engine tabs
    'エンジン・APU': 'Engine & APU',

    // Unit system toggle
    'メートル法': 'Metric',
    'ヤード・ポンド法': 'Imperial',

    // Disclaimer
    '免責事項': 'Disclaimer',
    '本ページに掲載されている航空機の仕様および性能データ等の情報は、一般的な参考情報として提供されています。これらのデータは、メーカーの公開資料、業界情報、および当社独自の推定に基づいて作成されており、一部には概算値や前提条件が含まれる場合があります。': 'The aircraft specifications, performance data, and related information presented on this page are provided for general informational purposes only. Data is compiled from publicly available manufacturer publications, industry sources, and internal estimates, and may include approximations or assumptions.',
    '航続距離、搭載量、速度などの性能数値は、機体の仕様や状態、気象条件、運用環境などのさまざまな要因によって変動するため、実際の数値は掲載内容と異なる場合があります。': 'Performance figures such as range, payload, and speed are influenced by variables including aircraft configuration, condition, weather, and operational factors. Actual results may vary from the values shown.',
    '本ページに掲載されている画像およびビジュアルは、AI生成または当社により作成されたイメージであり、特定の実機を正確に再現したものではありません。': 'All images and visual representations are AI-generated or created in-house for illustrative purposes only and do not depict any specific aircraft or guarantee accuracy in design or configuration.',
    'また、メーカーの更新、規制の変更、市場動向、地政学的要因などにより、掲載情報が最新でない場合があります。当社は、本情報の正確性、完全性、最新性についていかなる保証も行いません。': 'Information may become outdated due to manufacturer updates, regulatory changes, market conditions, or geopolitical factors. We do not guarantee the accuracy, completeness, or timeliness of the content provided.',
    '本情報は「現状有姿」で提供されるものであり、その利用によって生じたいかなる損害についても、当社は一切の責任を負いません。': 'All information is provided "as is" without warranties of any kind, and we assume no liability for errors, omissions, or outcomes resulting from its use.',

};

// Export for use in main.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = englishTranslations;
}
